import { RetroGame } from '../shared/types';

export const retroGames: RetroGame[] = [
  {
    id: 1,
    title: 'The Legend of Zelda',
    genre: ['Adventure', 'Action'],
    platform: 'Genesis',
    release_date: '1986-02-21',
    developer: 'Nintendo',
    publisher: 'Nintendo',
    description: 'Embark on a quest to rescue Princess Zelda in the kingdom of Hyrule.',
    cover_art_path: '/images/zelda.jpg',
    screenshots: ['/images/zelda_screen1.jpg', '/images/zelda_screen2.jpg'],
    rating: 4.9,
    popularity: 98,
    multiplayer: false,
    average_score: 9.2,
    review_count: 1200
  },
  {
    id: 2,
    title: 'Super Mario Bros.',
    genre: ['Platformer'],
    platform: 'Genesis',
    release_date: '1985-09-13',
    developer: 'Nintendo',
    publisher: 'Nintendo',
    description: 'Join Mario on a journey through the Mushroom Kingdom to rescue Princess Peach.',
    cover_art_path: '/images/mario.jpg',
    screenshots: ['/images/mario_screen1.jpg', '/images/mario_screen2.jpg'],
    rating: 4.8,
    popularity: 99,
    multiplayer: false,
    average_score: 9.5,
    review_count: 1350
  },
  {
    id: 3,
    title: 'Pac-Man',
    genre: ['Arcade'],
    platform: 'Arcade',
    release_date: '1980-05-22',
    developer: 'Namco',
    publisher: 'Namco',
    description: 'Navigate Pac-Man through a maze, eating pellets and avoiding ghosts.',
    cover_art_path: '/images/pacman.jpg',
    screenshots: ['/images/pacman_screen1.jpg', '/images/pacman_screen2.jpg'],
    rating: 4.7,
    popularity: 97,
    multiplayer: false,
    average_score: 8.7,
    review_count: 800
  },
  {
    id: 4,
    title: 'Street Fighter II',
    genre: ['Fighting'],
    platform: 'Arcade',
    release_date: '1991-03-01',
    developer: 'Capcom',
    publisher: 'Capcom',
    description: 'Challenge your opponents in this classic fighting game.',
    cover_art_path: '/images/sf2.jpg',
    screenshots: ['/images/sf2_screen1.jpg', '/images/sf2_screen2.jpg'],
    rating: 4.9,
    popularity: 95,
    multiplayer: true,
    average_score: 9.0,
    review_count: 900
  },
  {
    id: 5,
    title: 'Sonic the Hedgehog',
    genre: ['Platformer'],
    platform: 'Genesis',
    release_date: '1991-06-23',
    developer: 'Sega',
    publisher: 'Sega',
    description: 'Race through zones as Sonic to stop Dr. Robotnik.',
    cover_art_path: '/images/sonic.jpg',
    screenshots: ['/images/sonic_screen1.jpg', '/images/sonic_screen2.jpg'],
    rating: 4.8,
    popularity: 93,
    multiplayer: false,
    average_score: 8.9,
    review_count: 1100
  },
  {
    id: 6,
    title: 'Mega Man',
    genre: ['Action', 'Platformer'],
    platform: 'NES',
    release_date: '1987-12-17',
    developer: 'Capcom',
    publisher: 'Capcom',
    description: 'Help Mega Man defeat Dr. Wily and his evil robots.',
    cover_art_path: '/images/megaman.jpg',
    screenshots: ['/images/megaman_screen1.jpg', '/images/megaman_screen2.jpg'],
    rating: 4.7,
    popularity: 91,
    multiplayer: false,
    average_score: 8.5,
    review_count: 950
  },
  {
    id: 7,
    title: 'Castlevania',
    genre: ['Action', 'Adventure'],
    platform: 'NES',
    release_date: '1986-09-26',
    developer: 'Konami',
    publisher: 'Konami',
    description: 'Venture through Dracula’s castle to defeat him.',
    cover_art_path: '/images/castlevania.jpg',
    screenshots: ['/images/castlevania_screen1.jpg', '/images/castlevania_screen2.jpg'],
    rating: 4.6,
    popularity: 89,
    multiplayer: false,
    average_score: 8.3,
    review_count: 800
  },
  {
    id: 8,
    title: 'Final Fantasy',
    genre: ['RPG'],
    platform: 'NES',
    release_date: '1987-12-18',
    developer: 'Square',
    publisher: 'Square',
    description: 'Lead a group of heroes to defeat evil forces in a fantasy world.',
    cover_art_path: '/images/final_fantasy.jpg',
    screenshots: ['/images/final_fantasy_screen1.jpg', '/images/final_fantasy_screen2.jpg'],
    rating: 4.8,
    popularity: 94,
    multiplayer: false,
    average_score: 9.0,
    review_count: 1000
  },
  {
    id: 9,
    title: 'Donkey Kong',
    genre: ['Platformer', 'Arcade'],
    platform: 'Arcade',
    release_date: '1981-07-09',
    developer: 'Nintendo',
    publisher: 'Nintendo',
    description: 'Help Mario rescue the damsel from Donkey Kong.',
    cover_art_path: '/images/donkeykong.jpg',
    screenshots: ['/images/donkeykong_screen1.jpg', '/images/donkeykong_screen2.jpg'],
    rating: 4.7,
    popularity: 90,
    multiplayer: false,
    average_score: 8.8,
    review_count: 700
  },
  {
    id: 10,
    title: 'Metroid',
    genre: ['Action', 'Adventure'],
    platform: 'NES',
    release_date: '1986-08-06',
    developer: 'Nintendo',
    publisher: 'Nintendo',
    description: 'Navigate Samus through the planet Zebes to defeat the Space Pirates.',
    cover_art_path: '/images/metroid.jpg',
    screenshots: ['/images/metroid_screen1.jpg', '/images/metroid_screen2.jpg'],
    rating: 4.6,
    popularity: 88,
    multiplayer: false,
    average_score: 8.4,
    review_count: 850
  }
];
